Api prototype
mp-hl-2021/splinter pull request #3
Opened 2021-03-15 11:28 UTC by TsarN

2021-03-15 12:37 UTC, M0nsteR requested changes

2021-03-15 12:37 UTC, M0nsteR commented on internal/app/splinter/api/api.go
> +type Context struct {
I'd rather suggest using some other name here to avoid future conflicts with the standard package https://golang.org/pkg/context/

2021-03-15 12:37 UTC, M0nsteR commented on internal/app/splinter/api/api.go
> +	header := ctx.req.Header.Get("Authorization")
Please take a look at chat/api/api.go to implement the authorization functionality as middleware, cf. func (a *Api) authorize(handler http.HandlerFunc) http.HandlerFunc. Don't forget to return standard HTTP error codes.

2021-03-15 12:37 UTC, M0nsteR commented on internal/app/splinter/model/interface.go
> +	GetUserById(token Token, id string) (*User, error)
Why do you need to pass around a token? Once you know the actual user id, it should be sufficient for any usecases. Tokens come and go, especially JWTs. They are quite ephemeral..

2021-03-15 16:22 UTC, NekoNe requested changes

2021-03-15 16:22 UTC, NekoNe commented on internal/app/splinter/api/api.go
> +	"reflect"
It is very cool that you are already comfortable with Golang. 
But, please, try no to use reflect package in applications. It is ok when you are working with some relatively low-level programming, but it is not ok to find out object types in business applications on runtime.

2021-03-15 16:22 UTC, NekoNe commented on internal/app/splinter/api/api.go
> +	panic(t)
Why are you using panic() here?

2021-03-15 16:22 UTC, NekoNe commented on internal/app/splinter/api/api.go
> +		log.Fatal(err)
Please, consider not to use panics.

2021-03-15 16:22 UTC, NekoNe commented on internal/app/splinter/api/api.go
> +func (a *Api) MakeHandler(name string) http.Handler {
It is an interesting and cool way to do handlers. But could you explain the WHY of this solution?
For me it just contradicts the philosophy of Go. If you are trying to reduce the number of lines, you could use middleware technique and place it around entire router.

2021-03-15 16:22 UTC, NekoNe commented on internal/app/splinter/model/interface.go
> +type UserInterface interface {
Could you exclude backend and model from this PR, please? It is not related to API. And too much to review in one PR

2021-05-07 10:36 UTC, TsarN commented
Sorry for the delay. Will refactor as separate PRs.

2021-05-07 10:36 UTC, closed without merging